# Generated by Django 5.2.17 on 2026-08-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_start", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rooms.room",
                        verbose_name="Номер отеля",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["date_start"],
            },
        ),
    ]
